services:
    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=dbMySql
            - MYSQL_ROOT_PASSWORD= skimate
    php:
        build: "./DockerfilePHP"
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80"
        environment:
            - MYSQL_HOST=dbMySql
            - MYSQL_USER=aswan
            - MYSQL_PASSWORD= password_skimate
            - MYSQL_DATABASE=DB
    dbMySql:
        image: mysql:8.4.1
        environment:
            MYSQL_ROOT_PASSWORD: skimate
            MYSQL_DATABASE: DB
            MYSQL_USER: aswan
            MYSQL_PASSWORD: password_skimate