services:
    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - MYSQL_ROOT_PASSWORD=skimate-password

    php:
        build: DockerfilePHP
        volumes:
            - ../SkiMateProject:/var/www/html
        ports:
            - "8080:80"
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USER=skimate_user
            - MYSQL_PASSWORD=skimate
            - MYSQL_DATABASE=skimate

    mysql:
        image: mysql:8.0.21
        environment:
            - MYSQL_ROOT_PASSWORD=skimate-password
            - MYSQL_DATABASE=skimate
            - MYSQL_USER=skimate_user
            - MYSQL_PASSWORD=skimate
        ports:
            - "3306:3306"

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: skimate
            MONGO_INITDB_ROOT_PASSWORD: skimate

volumes:
    mysql_data: