services:
    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - MYSQL_ROOT_PASSWORD=skimate-password

    php:
        build:
            context: .
            dockerfile: DockerfilePHP/Dockerfile
        volumes:
            - ../SkiMateProject:/var/www/html
        ports:
            - "8080:80"
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USER=skimate_user
            - MYSQL_PASSWORD=skimate
            - MYSQL_DATABASE=skimate
        depends_on:
            - mysql
            - mongo

    mysql:
        image: mysql:8.0.21
        environment:
            - MYSQL_ROOT_PASSWORD=skimate-password
            - MYSQL_DATABASE=skimate
            - MYSQL_USER=skimate_user
            - MYSQL_PASSWORD=skimate
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    mongo:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=skimate
            - MONGO_INITDB_ROOT_PASSWORD=skimate
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=skimate
            - ME_CONFIG_MONGODB_ADMINPASSWORD=skimate
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_BASICAUTH_USERNAME=skimate
            - ME_CONFIG_BASICAUTH_PASSWORD=skimate
        ports:
            - "8082:8081"


volumes:
    mysql_data:
    mongo_data:
