services:
    server:
        container_name: server_skimate
        image: 'nginx:1.28.0-alpine3.21'
        volumes:
            - ./SkiMateProject:/var/www/SkiMateProject
            - ./.docker/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        ports:
            - '8081:80'
        networks:
            - network

    php_skimate:
        user: "1000"
        build: ./.docker/php
        working_dir: /www/SkiMateProject
        volumes:
            - ../SkiMateProject:/www/SkiMateProject
            - ../SkiMateProject/var:/www/SkiMateProject/var
            - .docker/php.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
        ports:
            - "8080:80"
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USER=skimate_user
            - MYSQL_PASSWORD=skimate
            - MYSQL_DATABASE=skimate
        networks:
            - network

    mysql_skimate:
        image: mysql:8.4.5
        environment:
            - MYSQL_ROOT_PASSWORD=skimate-password
            - MYSQL_DATABASE=skimate
            - MYSQL_USER=skimate_user
            - MYSQL_PASSWORD=skimate
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - network

    mongo_skimate:
        image: mongo:8.0
        environment:
            - MONGO_INITDB_ROOT_USERNAME=skimate
            - MONGO_INITDB_ROOT_PASSWORD=skimate
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        networks:
            - network


volumes:
    mysql_data:
    mongo_data:
networks:
    network:
        driver: bridge
