version: '3.8'

services:
    sonarqube:
        image: sonarqube:community
        container_name: sonarqube
        depends_on:
            - db
        ports:
            - "9001:9000"        # Vous accéderez à l'UI sur http://localhost:9001
        environment:
            SONAR_JDBC_URL:       jdbc:postgresql://db:5432/sonarqube
            SONAR_JDBC_USERNAME:  skimate
            SONAR_JDBC_PASSWORD:  skimate123
        volumes:
            - sonardata:/opt/sonarqube/data
            - sonarext:/opt/sonarqube/extensions
            - sonarlogs:/opt/sonarqube/logs
        healthcheck:
            test: ["CMD" , "curl" , "-f" , "http://localhost:9000/api/system/status"]
            interval: 10s
            retries: 10
            start_period: 30s
            timeout: 5s
        networks:
            - sonar_net

    db:
        image: postgres:17-alpine
        container_name: sonardb
        environment:
            POSTGRES_USER:     skimate
            POSTGRES_PASSWORD: skimate123
            POSTGRES_DB:       sonarqube
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - sonar_net

    scanner:
        image: sonarsource/sonar-scanner-cli
        container_name: sonar_scanner
        depends_on:
            - sonarqube
        environment:
            SONAR_HOST_URL: "http://sonarqube:9000"
        volumes:
            - ./:/usr/src
        networks:
            - sonar_net

volumes:
    sonardata:
    sonarext:
    sonarlogs:
    dbdata:

networks:
    sonar_net:
        driver: bridge
