services:
    sonarqubecicd:
        image: sonarqube:community
        depends_on:
            - dbsonarcicd
        ports:
            - "9000:9000"
        environment:
            - SONAR_JDBC_URL=jdbc:postgresql://dbsonarcicd:5432/sonarqube
            - SONAR_JDBC_USERNAME=skimate
            - SONAR_JDBC_PASSWORD=skimate123
        volumes:
            - sonarcicd_data:/opt/sonarqube/data
            - sonarcicd_extensions:/opt/sonarqube/extensions
            - sonarcicd_logs:/opt/sonarqube/logs
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/api/system/status" ]
            interval: 10s
            retries: 10
            start_period: 30s
            timeout: 5s

    dbsonarcicd:
        image: postgres:17-alpine3.21
        container_name: dbsonarcicd
        environment:
            - POSTGRES_USER=skimate
            - POSTGRES_PASSWORD=skimate123
            - POSTGRES_DB=sonarqube
        volumes:
            - dbsonarcicd:/var/lib/postgresql/data
        ports:
            - "5434:5432"

    sonar-scannercicd:
        image: sonarsource/sonar-scanner-cli
        container_name: sonar-scannercicd
        depends_on:
            sonarqubecicd:
                condition: service_healthy
        environment:
            SONAR_HOST_URL: "http://sonarqubecicd:9000"
            #SONAR_TOKEN: "sqp_f40c3cb06488a5e6177165f6b72fc2cdadfd3adf"
        volumes:
            - ../symfony:/usr/src
volumes:
        sonarcicd_data:
        sonarcicd_extensions:
        sonarcicd_logs:
        dbsonarcicd:




