services:
    server:
        container_name: server_skimate
        image: 'nginx:1.28.0-alpine3.21'
        ports:
            - "9000:80"
        volumes:
            - ./symfony:/var/www/symfony
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - network
    php_skimate:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        working_dir: /var/www/symfony
        volumes:
            - ./symfony:/var/www/symfony
            - symfony_var:/var/www/symfony/var
            - ./symfony/public/uploads:/var/www/symfony/public/uploads
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini:ro
        ports:
            - "8000:8000"

        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USER=skimate_user
            - MYSQL_PASSWORD=skimate
            - MYSQL_DATABASE=skimate
            - JWT_PASSPHRASE=${JWT_PASSPHRASE}
        networks:
            - network

    mysql_skimate:
        image: mysql:8.4.5
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=skimate-password
            - MYSQL_DATABASE=skimate
            - MYSQL_USER=skimate_user
            - MYSQL_PASSWORD=skimate
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - network

    mongo_skimate:
        image: mongo:8.0
        environment:
            - MONGO_INITDB_ROOT_USERNAME=skimate
            - MONGO_INITDB_ROOT_PASSWORD=skimate
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        networks:
            - network

    mongo_express:
        image: mongo-express:latest
        container_name: mongo_express
        ports:
            - "8082:8081"
        environment:
            # connexion à MongoDB avec user/password
            ME_CONFIG_MONGODB_URL: "mongodb://skimate:skimate@mongo_skimate:27017"
            # activer l’authentification web
            ME_CONFIG_BASICAUTH_USERNAME: skimate
            ME_CONFIG_BASICAUTH_PASSWORD: skimate
        depends_on:
            - mongo_skimate
        networks:
            - network

volumes:
    mysql_data:
    mongo_data:
    symfony_var:
networks:
    network:
        driver: bridge
