nelmio_cors:
    defaults:
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/': ~
