security:
    role_hierarchy:
        ROLE_USER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_ADMIN]
        ROLE_MODERATOR: [ROLE_MODERATOR]

    password_hashers:
        App\Entity\User: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider_email:
            entity:
                class: App\Entity\Users
                property: email

        app_user_provider_id:
            entity:
                class: App\Entity\Users
                property: id

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login$
            stateless: true
            provider: app_user_provider_email
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: 'App\Security\JsonLoginSuccessHandler'
                failure_handler: 'App\Security\JsonLoginFailureHandler'

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider_id
            jwt: ~
            entry_point: App\Security\ApiAuthenticationEntryPoint
            refresh_jwt:
                check_path: /api/token/refresh

    access_control:
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: PUBLIC_ACCESS }
        - { path: ^/api/comment/.*, roles: ROLE_ADMIN }

services:
    App\Security\JsonLoginSuccessHandler:
        class: App\Security\JsonLoginSuccessHandler
        arguments:
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
    App\Security\JsonLoginFailureHandler:
        class: App\Security\JsonLoginFailureHandler
    App\Security\ApiAccessDeniedHandler:
        class: App\Security\ApiAccessDeniedHandler
    App\Security\ApiAuthenticationEntryPoint:
        class: App\Security\ApiAuthenticationEntryPoint